const seedData = [
  {
    user_id: 63,
    story_id: "70e9e760-45ec-4fe7-a405-9ec57cf83587",
    emotion: null,
    genre: "Mystery",
    title: "The Mansion Mystery",
    content: "Detective Smith stared at the crime scene, trying to make sense of the clues. It was a dark and stormy night, and the old mansion was shrouded in mystery. He knew this case would test his skills like never before.",
  },
  {
    user_id: 62,
    story_id: "38dbbd48-720d-4f71-94e3-6c1c4860e0f2",
    emotion: null,
    genre: "Science Fiction",
    title: "The Colonization of Mars",
    content: "In the year 3025, humans had colonized Mars. Advanced technology had made it possible for humans to build thriving cities on the Red Planet. John, a brilliant scientist, was working on a project to terraform Mars and make it habitable for future generations.",
  },
  {
    user_id: 61,
    story_id: "3f52aa34-dbf9-42e4-977f-eedae1332e3a",
    emotion: null,
    genre: "Fantasy",
    title: "The Magical Forest",
    content: "Once upon a time in a magical forest, there lived a wise old wizard named Merlin. He had a long white beard and a pointed hat, and his cottage was hidden deep within the woods. Merlin was known throughout the land for his incredible knowledge of spells and potions.",
  },
  {
    user_id: 63,
    story_id: "a5c40a68-9c22-429e-8f61-274b82694764",
    emotion: null,
    genre: "Adventure",
    title: "The Knight's Quest",
    content: "Once upon a time, in a land far away, there was a brave knight named Sir Arthur. He embarked on a quest to rescue a captured princess from the clutches of a fearsome dragon.",
  },
  {
    user_id: 65,
    story_id: "7f06d8a2-8ff5-4c2b-9e46-59f212a59851",
    emotion: null,
    genre: "Romance",
    title: "Sunset Dreams",
    content: "In a quiet village by the sea, a young artist named Emily painted the most beautiful sunsets. Her art captured the hearts of all who saw it and brought joy to her fellow villagers.",
  },
  {
    user_id: 66,
    story_id: "90b01bc1-56f9-4cc4-9099-7a4e990ed9e9",
    emotion: null,
    genre: "Drama",
    title: "Cross-Country Adventure",
    content: "In the bustling city of New York, a group of friends embarked on a road trip of a lifetime. Their adventures took them from the bright lights of Times Square to the serene beauty of the Grand Canyon.",
  },
  {
    user_id: 67,
    story_id: "f3b60b9f-5ad0-4be0-8654-dab3b56f147e",
    emotion: null,
    genre: "Drama",
    title: "Culinary Delights",
    content: "In the heart of Paris, a talented chef named Sophie prepared exquisite dishes that delighted diners from around the world. Her culinary creations were a symphony of flavors that left a lasting impression.",
  },
  {
    user_id: 68,
    story_id: "847fc65a-783d-47c1-b7f2-fad4f313a924",
    emotion: null,
    genre: "Fantasy",
    title: "The Sorcerer's Quest",
    content: "In a world filled with magic, a young sorcerer named Liam embarked on a quest to unlock the secrets of an ancient spell. His journey led him to hidden realms and unimaginable challenges.",
  },
  {
    user_id: 69,
    story_id: "05f9ff87-90e6-41c2-bb4d-6a4be0c582ae",
    emotion: null,
    genre: "Drama",
    title: "Behind the Scenes",
    content: "On the set of a blockbuster film, director Mia worked tirelessly to bring a story to life. Her vision and dedication transformed the script into a cinematic masterpiece.",
  },
  {
    user_id: 70,
    story_id: "c64d5a80-9c3e-4620-8c94-b4b74580e2a2",
    emotion: null,
    genre: "Science Fiction",
    title: "Galactic Explorers",
    content: "In a distant galaxy, a spaceship named Seraphim embarked on a journey to explore uncharted worlds. Captain Noah and his crew encountered strange creatures and unraveled cosmic mysteries.",
  },
  {
    user_id: 61,
    story_id: "ad13e1c4-9f11-47d0-8e65-25d1545b82c1",
    emotion: null,
    genre: "Dystopian",
    title: "Survivors",
    content: "Amidst the chaos of a post-apocalyptic world, a group of survivors banded together to build a new society. They faced challenges, made sacrifices, and discovered the resilience of the human spirit.",
  },
  {
    user_id: 62,
    story_id: "9d78a0c0-6f4e-4b8d-8279-fd3d5fb7cdea",
    emotion: null,
    genre: "Drama",
    title: "Harvest of Dreams",
    content: "In the serene countryside, a young farmer named Isabella nurtured her crops with love and dedication. Her farm flourished, and her produce was renowned for its exceptional quality.",
  },
];

module.exports = { seedData };
