module.exports = [
  {
    id: '4f6cf151-8bce-4a47-bf52-e6b1a5a63e14', 
    username: 'user2',
    github_id: null, 
    avatar_url: null, 
    password: 'password2',
    password2: 'password2',
    email: 'user2@example.com',
    first_name: 'Jane',
    last_name: 'Smith',
    pen_first_name: 'Peter',
    pen_last_name: 'Johnson',
    bio: "Novelist weaving tales of mystery and intrigue that keep readers on the edge of their seats."
  },
  {
    id: '5e2f0e1d-3e94-4e1a-ae8d-1e5c2043e6d2', 
    username: 'user1',
    github_id: null, 
    avatar_url: null, 
    password: 'password1',
    password2: 'password1',
    email: 'user1@example.com',
    first_name: 'John',
    last_name: 'Doe',
    pen_first_name: 'Penelope',
    pen_last_name: 'Drake',
    bio: "Poet with a heart full of emotions and a pen dipped in ink."
  },
  {
    id: '9a8c7b6d-5e4f-3a2b-1c0d-7e6f5a4b3c2a', 
    username: 'user3',
    github_id: null, 
    avatar_url: null, 
    password: 'password3',
    password2: 'password3',
    email: 'user3@example.com',
    first_name: 'Robert',
    last_name: 'Johnson',
    pen_first_name: 'Olivia',
    pen_last_name: 'Smith',
    bio: "Wordsmith crafting eloquent prose that touches hearts and minds."
  },
  {
    id: '1b2c3d4e-5f6a-7b8c-9d0e-a1b2c3d4e5f6', 
    username: 'user4',
    github_id: null, 
    avatar_url: null, 
    password: 'password4',
    password2: 'password4',
    email: 'user4@example.com',
    first_name: 'Emily',
    last_name: 'Brown',
    pen_first_name: 'Ethan',
    pen_last_name: 'Davis',
    bio: "Author of children's books, bringing joy and laughter to young readers."
  },
  {
    id: 'a1b2c3d4-5e6f-7a8b-9c0d-1e2f3a4b5c6', 
    username: 'user5',
    github_id: null, 
    avatar_url: null, 
    password: 'password5',
    password2: 'password5',
    email: 'user5@example.com',
    first_name: 'Michael',
    last_name: 'Miller',
    pen_first_name: 'Sophia',
    pen_last_name: 'Clark',
    bio: "Dedicated journalist on a mission to uncover the truth and share untold stories."
  },
  {
    id: 'b1c2d3e4-f5a6-7b8c-9d0e-1a2b3c4d5e6', 
    username: 'user6',
    github_id: null, 
    avatar_url: null, 
    password: 'password6',
    password2: 'password6',
    email: 'user6@example.com',
    first_name: 'William',
    last_name: 'Wilson',
    pen_first_name: 'Ava',
    pen_last_name: 'Rodriguez',
    bio: "Romance writer creating tales of love that transport readers to far-off places."
  },
  {
    id: 'c1d2e3f4-g5a6-7b8c-9d0e-1a2b3c4d5e6', 
    username: 'user7',
    github_id: null, 
    avatar_url: null, 
    password: 'password7',
    password2: 'password7',
    email: 'user7@example.com',
    first_name: 'Elizabeth',
    last_name: 'Taylor',
    pen_first_name: 'Liam',
    pen_last_name: 'Martinez',
    bio: "Scriptwriter for film and television, breathing life into unforgettable characters."
  },
  {
    id: 'd1e2f3a4-b5c6-7d8e-9f0a-1b2c3d4e5f6', 
    username: 'user8',
    github_id: null, 
    avatar_url: null, 
    password: 'password8',
    password2: 'password8',
    email: 'user8@example.com',
    first_name: 'David',
    last_name: 'Anderson',
    pen_first_name: 'Mia',
    pen_last_name: 'Martinez',
    bio: "Passionate writer exploring the realms of fantasy and science fiction."
  },
  {
    id: 'e1f2a3b4-c5d6-7e8f-9a0b-1c2d3e4f5a6', 
    username: 'user9',
    github_id: null, 
    avatar_url: null, 
    password: 'password9',
    password2: 'password9',
    email: 'user9@example.com',
    first_name: 'Sarah',
    last_name: 'Thomas',
    pen_first_name: 'Noah',
    pen_last_name: 'Wilson',
    bio: "Literary explorer delving into the depths of human nature through thought-provoking essays."
  },
  {
    id: 'f1a2b3c4-d5e6-7f8a-9b0c-1d2e3f4a5b6',
    username: 'user10',
    github_id: null, 
    avatar_url: null, 
    password: 'password10',
    password2: 'password10',
    email: 'user10@example.com',
    first_name: 'James',
    last_name: 'Jackson',
    pen_first_name: 'Isabella',
    pen_last_name: 'Hall',
    bio: "Blogger sharing insights, experiences, and musings on life's journey."
  },
];
