module.exports = [
  {
    username: 'user2',
    githubId: null, 
    googleId: null,
    facebookId: null,
    avatar_url: null, 
    password: 'password2',
    password2: 'password2',
    email: 'user2@example.com',
    first_name: 'Jane',
    last_name: 'Smith',
    pen_first_name: 'Peter',
    pen_last_name: 'Johnson',
    bio: "Novelist weaving tales of mystery and intrigue that keep readers on the edge of their seats."
  },
  {
    username: 'user1',
    githubId: null, 
    googleId: null,
    facebookId: null,
    avatar_url: null, 
    password: 'password1',
    password2: 'password1',
    email: 'user1@example.com',
    first_name: 'John',
    last_name: 'Doe',
    pen_first_name: 'Penelope',
    pen_last_name: 'Drake',
    bio: "Poet with a heart full of emotions and a pen dipped in ink."
  },
  {
    username: 'user3',
    githubId: null,  
    googleId: null,
    facebookId: null,
    avatar_url: null, 
    password: 'password3',
    password2: 'password3',
    email: 'user3@example.com',
    first_name: 'Robert',
    last_name: 'Johnson',
    pen_first_name: 'Olivia',
    pen_last_name: 'Smith',
    bio: "Wordsmith crafting eloquent prose that touches hearts and minds."
  },
  {
    username: 'user4',
    githubId: null, 
    googleId: null,
    facebookId: null,
    avatar_url: null, 
    password: 'password4',
    password2: 'password4',
    email: 'user4@example.com',
    first_name: 'Emily',
    last_name: 'Brown',
    pen_first_name: 'Ethan',
    pen_last_name: 'Davis',
    bio: "Author of children's books, bringing joy and laughter to young readers."
  },
  {
    username: 'user5',
    githubId: null,  
    googleId: null,
    facebookId: null,
    avatar_url: null, 
    password: 'password5',
    password2: 'password5',
    email: 'user5@example.com',
    first_name: 'Michael',
    last_name: 'Miller',
    pen_first_name: 'Sophia',
    pen_last_name: 'Clark',
    bio: "Dedicated journalist on a mission to uncover the truth and share untold stories."
  },
  {
    username: 'user6',
    githubId: null,  
    googleId: null,
    facebookId: null,
    avatar_url: null, 
    password: 'password6',
    password2: 'password6',
    email: 'user6@example.com',
    first_name: 'William',
    last_name: 'Wilson',
    pen_first_name: 'Ava',
    pen_last_name: 'Rodriguez',
    bio: "Romance writer creating tales of love that transport readers to far-off places."
  },
  {
    username: 'user7',
    githubId: null, 
    googleId: null,
    facebookId: null,
    avatar_url: null, 
    password: 'password7',
    password2: 'password7',
    email: 'user7@example.com',
    first_name: 'Elizabeth',
    last_name: 'Taylor',
    pen_first_name: 'Liam',
    pen_last_name: 'Martinez',
    bio: "Scriptwriter for film and television, breathing life into unforgettable characters."
  },
  {
    username: 'user8',
    githubId: null, 
    googleId: null,
    facebookId: null,
    avatar_url: null, 
    password: 'password8',
    password2: 'password8',
    email: 'user8@example.com',
    first_name: 'David',
    last_name: 'Anderson',
    pen_first_name: 'Mia',
    pen_last_name: 'Martinez',
    bio: "Passionate writer exploring the realms of fantasy and science fiction."
  },
  {
    username: 'user9',
    githubId: null, 
    googleId: null,
    facebookId: null,
    avatar_url: null, 
    password: 'password9',
    password2: 'password9',
    email: 'user9@example.com',
    first_name: 'Sarah',
    last_name: 'Thomas',
    pen_first_name: 'Noah',
    pen_last_name: 'Wilson',
    bio: "Literary explorer delving into the depths of human nature through thought-provoking essays."
  },
  {
    username: 'user10',
    githubId: null, 
    googleId: null,
    facebookId: null,
    avatar_url: null, 
    password: 'password10',
    password2: 'password10',
    email: 'user10@example.com',
    first_name: 'James',
    last_name: 'Jackson',
    pen_first_name: 'Isabella',
    pen_last_name: 'Hall',
    bio: "Blogger sharing insights, experiences, and musings on life's journey."
  },
];
