module.exports = [{
    id: 'ea576a0a-3632-11ee-be56-0242ac120002',
    username: 'user1',
    password: 'password1',
    password2: 'password1',
    email: 'user1@example.com',
    first_name: 'John',
    last_name: 'Doe',
    pen_first_name: 'Penelope',
    pen_last_name: 'Drake',
    bio:"Poet with a heart full of emotions and a pen dipped in ink.",
    links:'facebook.com'
  },
  {
    id: 'f6afd2ce-3632-11ee-be56-0242ac120002',
    username: 'user2',
    password: 'password2',
    password2: 'password2',
    email: 'user2@example.com',
    first_name: 'Jane',
    last_name: 'Smith',
    pen_first_name: 'Peter',
    pen_last_name: 'Johnson',
    bio:"Novelist weaving tales of mystery and intrigue that keep readers on the edge of their seats.",
    links:'facebook.com'
  },
  {
    id: 'ff9b5746-3632-11ee-be56-0242ac120002',
    username: 'user3',
    password: 'password3',
    password2: 'password3',
    email: 'user3@example.com',
    first_name: 'Robert',
    last_name: 'Johnson',
    pen_first_name: 'Olivia',
    pen_last_name: 'Smith',
    bio:"Wordsmith crafting eloquent prose that touches hearts and minds.",
    links:'facebook.com'
  },
  {
    id: '09008dce-3633-11ee-be56-0242ac120002',
    username: 'user4',
    password: 'password4',
    password2: 'password4',
    email: 'user4@example.com',
    first_name: 'Emily',
    last_name: 'Brown',
    pen_first_name: 'Ethan',
    pen_last_name: 'Davis',
    bio:"Author of children's books, bringing joy and laughter to young readers.",
    links:'Facebook.com'
  },
  {
    id: '1e1fe9f2-3633-11ee-be56-0242ac120002',
    username: 'user5',
    password: 'password5',
    password2: 'password5',
    email: 'user5@example.com',
    first_name: 'Michael',
    last_name: 'Miller',
    pen_first_name: 'Sophia',
    pen_last_name: 'Clark',
    bio:"Dedicated journalist on a mission to uncover the truth and share untold stories.",
    links:'Facebook.com'
  },
  {
    id: '33246760-3633-11ee-be56-0242ac120002',
    username: 'user6',
    password: 'password6',
    password2: 'password6',
    email: 'user6@example.com',
    first_name: 'William',
    last_name: 'Wilson',
    pen_first_name: 'Ava',
    pen_last_name: 'Rodriguez',
    bio:"Romance writer creating tales of love that transport readers to far-off places.",
    links:'Facebook.com'
  },
  {
    id: '42001db0-3633-11ee-be56-0242ac120002',
    username: 'user7',
    password: 'password7',
    password2: 'password7',
    email: 'user7@example.com',
    first_name: 'Elizabeth',
    last_name: 'Taylor',
    pen_first_name: 'Liam',
    pen_last_name: 'Martinez',
    bio:"Scriptwriter for film and television, breathing life into unforgettable characters.",
    links:'Facebook.com'
  },
  {
    id: '42001db0-3633-11ee-be56-0242ac120007',
    username: 'user8',
    password: 'password8',
    password2: 'password8',
    email: 'user8@example.com',
    first_name: 'David',
    last_name: 'Anderson',
    pen_first_name: 'Mia',
    pen_last_name: 'Martinez',
    bio:"Passionate writer exploring the realms of fantasy and science fiction.",
    links:'Facebook.com'
  },
  {
    id: '51a65068-3633-11ee-be56-0242ac120002',
    username: 'user9',
    password: 'password9',
    password2: 'password9',
    email: 'user9@example.com',
    first_name: 'Sarah',
    last_name: 'Thomas',
    pen_first_name: 'Noah',
    pen_last_name: 'Wilson',
    bio:"Literary explorer delving into the depths of human nature through thought-provoking essays.",
    links:'Facebook.com'
  },
  {
    id: '5a4988b6-3633-11ee-be56-0242ac120002',
    username: 'user10',
    password: 'password10',
    password2: 'password10',
    email: 'user10@example.com',
    first_name: 'James',
    last_name: 'Jackson',
    pen_first_name: 'Isabella',
    pen_last_name: 'Hall',
    bio:"Blogger sharing insights, experiences, and musings on life's journey.",
    links:'Facebook.com'
  }
];
